### ISSUE TITLE
Node inconsistent with parents

### ISSUE THREAD

**Issue by Hintza** [Hintza/SinNombreVirus#1]
Error when running constant CJS model:

`module glm loaded
Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
  Error in node z[28,3]
Node inconsistent with parents`

Is it referring to just the latent state node or referring to multiple nodes? The node varies with each run.

**Comment by angieluis** [comment]
I was getting this error too when I ran the first part where they didn’t put in the extra information about latent state, z. When I ran the next bit of code that puts in info about z, this error went away. I’m not sure what it’s about.

**Comment by Hintza** [comment]
The code ran but still bothered by this issue.
