### ISSUE TITLE
Multistate code - walkthrough

### ISSUE THREAD

**Issue by Hintza** [Hintza/SinNombreVirus#4]

**Comment by Hintza** [comment]
Coding this was like foreign language inception. I'll need some time to stew on this. Received this error code when running the model:

Compilation error on line 53.
Unknown variable Y
Either supply values for this variable with the data
or define it  on the left hand side of a relation.

In reference to this chunk:
` # likelihood
        for (i in 1:nind) {
          
          # define latent state at first capture
          z[i, f[i]] <- Y[i, f[i]]
          
          for (t in (f[i] + 1):n.occ) {
            
            # state process - draw S(t) given S(t - 1)
            z[i, t] ~ dcat(ps[z[i, t - 1], i, t - 1, ])
            
            # observation process - draw O(t) given S(t)
            y[i, t] ~ dcat(po[z[i, t], i, t -1, ])

          } # t
        } # i`

**Comment by angieluis** [comment]
It’s saying it doesn’t recognize Y in your first line in the loop. Should it be lowercase?
