### ISSUE TITLE
Tag ID and fate both equal - 9

### ISSUE THREAD

**Issue by Hintza** [Hintza/SinNombreVirus#7]
@angieluis what do we do about tags and fates that are both -9.  They have species ID but I have no idea how you would assign them to a capture history since the info isn't specific to a tag.  I plan to omit for now but can revisit after we discuss.  There are 316 instances for which this is an issue.

**Comment by angieluis** [comment]
You have to omit the -9 for tag.  But you should be able to deal w -9 for fate.
