### ISSUE TITLE
Issue with last for loop for capture histories

### ISSUE THREAD

**Issue by Hintza** [Hintza/SinNombreVirus#9]
@angieluis , I'm working through the colossal nested for loops and this error keeps popping up:

`Error in CH.list[[m]][i, d] <- ifelse(dat$snv_adj == 0, 1, ifelse(dat$snv_adj ==  : 
  number of items to replace is not a multiple of replacement length`

I think this is likely due to the fact that we replaced everything in the SNV adjusted column with NA (to estimate infection at a later time). I'm going to replace with a value and see where that gets us.

**Comment by angieluis** [comment]
It’s probably because what is being plugged in is more than one number. check and see what the values are for m, i and d when the code breaks and see what the if else returns.
